name       : rtv
version    : 1.21.0
release    : 6
source     :
    - https://github.com/michael-lazar/rtv/archive/v1.21.0.tar.gz : 7e6a8de7b3e05b93d135cd2aa869b3d20f6ec26073a586e3595cff7f2df1aafa
license    : MIT
component  : network.news
summary    : Browse Reddit from your terminal
description: |
    RTV provides an interface to view and interact with reddit from your terminal. It's compatible with most terminal emulators on Linux.
builddeps  :
    - python-setuptools
rundeps    :
    - python-beautifulsoup4
    - python-decorator
    - python-kitchen
    - python-mailcap-fix
    - python-setuptools
setup      : |
    %python_setup
install    : |
    %python_install
